name: MobMeat
main: me.shzylo.mobmeat.MobMeat
authors: [Shzylo]
website: http://shzylogames.elementfx.com/
version: 0.2

commands:
  mobmeat:
    description: Reload MobMeat
    aliases: [mobm, mmeat, mm]
    
permissions:
  mobmeat.*:
    description: all MobMeat commands
    default: op
    children:
      mobmeat.reload: true
      mobmeat.sulphur: true

  mobmeat.reload:
    description: allows you to reload MobMeat
    default: op
    
  mobmeat.sulphur:
    description: allows a player to have sulphur as an explosive
    default: true
